# Nombre del flujo: Se encarga de enviar la app a producción (Render)
name: CD - Deploy Render

on:
  workflow_run:
    # Este flujo se activa automáticamente cuando el flujo de CI termina
    workflows: ["CI - Build and Test"]
    types:
      - completed

jobs:
  deploy:
    # Condición de seguridad: Solo se ejecuta si el CI terminó con éxito
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          # Envía una petición POST a la URL de Render (guardada en Secretos) para iniciar el despliegue
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}